create table category (category_id integer not null, item_count integer not null, category_name varchar(255), tag_count integer not null, discord_user_discord_user_id integer, primary key (category_id));
create table category_tags (categories_category_id integer not null, tags_tag_id integer not null, primary key (categories_category_id, tags_tag_id));
create table discord_user (discord_user_id integer not null, discord_user_name varchar(255), user_id varchar(255), primary key (discord_user_id));
create table hibernate_sequences (sequence_name varchar(255) not null, next_val bigint, primary key (sequence_name));
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
insert into hibernate_sequences(sequence_name, next_val) values ('default',0);
create table item (item_id integer not null, description varchar(255), link varchar(255), message_id varchar(255), modal boolean, item_name varchar(255), time bigint, discord_user_discord_user_id integer, primary key (item_id));
create table item_categories (items_item_id integer not null, categories_category_id integer not null, primary key (items_item_id, categories_category_id));
create table item_tags (items_item_id integer not null, tags_tag_id integer not null, primary key (items_item_id, tags_tag_id));
create table tag (tag_id integer not null, item_count integer not null, tag_name varchar(255), discord_user_discord_user_id integer, primary key (tag_id));
alter table category add constraint FKamhakqiv2aa4efp3i48gg2n8h foreign key (discord_user_discord_user_id) references discord_user;
alter table category_tags add constraint FKdqsxsgtc7fom2r0ejqrx144gc foreign key (tags_tag_id) references tag;
alter table category_tags add constraint FKfkv6k9vhw252x52wmj7xix9ed foreign key (categories_category_id) references category;
alter table item add constraint FKm5eunn56nxdpkmy5976ndu9jw foreign key (discord_user_discord_user_id) references discord_user;
alter table item_categories add constraint FKhgp0fm3rhrb2caoy2hrp6ohwk foreign key (categories_category_id) references category;
alter table item_categories add constraint FKmsrbcmtkwo0sbehm0c3jcrwx6 foreign key (items_item_id) references item;
alter table item_tags add constraint FKkk1d6iidm6ixyjjbgqrgsp66c foreign key (tags_tag_id) references tag;
alter table item_tags add constraint FKf9l3to0ge3gd6lpgnsjgwi3jv foreign key (items_item_id) references item;
alter table tag add constraint FK6rbtub3jdtmoitwjqjn4xcvrp foreign key (discord_user_discord_user_id) references discord_user;
